# **TensorFlow Fundamentals**

### Part 1: Theoretical Questions

#### Tc: What are the different data structures used in TensorFlow? Give some examples.

TensorFlow uses several data structures to represent and manipulate data:

1. **Tensors**: The primary data structure, representing n-dimensional arrays. 
   - Example: `tf.constant([1, 2, 3])` creates a 1D tensor.

2. **Variables**: Mutable tensors used for storing and updating parameters during training.
   - Example: `tf.Variable([1, 2, 3])` creates a variable.

3. **Datasets**: Represent sequences of data, usually used for input pipelines.
   - Example: `tf.data.Dataset.from_tensor_slices([1, 2, 3])` creates a dataset.

4. **Sparse Tensors**: Efficiently represent tensors with a majority of elements being zero.
   - Example: `tf.sparse.SparseTensor(indices=[[0, 1]], values=[1], dense_shape=[3, 4])`.

5. **Ragged Tensors**: Handle tensors with varying shapes across one dimension.
   - Example: `tf.ragged.constant([[1, 2, 3], [4, 5], [6]])`.


#### Cc: How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

- **TensorFlow Constant**: Immutable once defined, used for storing fixed values.

- **TensorFlow Variable**: Mutable, used for parameters that need to change during training (e.g., weights in a neural network).


In [1]:
import tensorflow as tf
const = tf.constant([1, 2, 3])
print(const)

2024-08-04 09:19:48.833593: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-04 09:19:49.012897: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-04 09:19:49.067664: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-04 09:19:49.397437: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-04 09:19:52.097008: W tensorflow/compiler/tf2

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


I0000 00:00:1722743397.047661    6014 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1722743397.472539    6014 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1722743397.472608    6014 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1722743397.479730    6014 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1722743397.479808    6014 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:0

050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6


In [4]:
var = tf.Variable([1, 2, 3])
var.assign([4, 5, 6])
print(var)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>


#### =c: Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

- **Matrix Addition**: Adds corresponding elements of two matrices.
- **Matrix Multiplication**: Performs dot product of two matrices.
- **Element-wise Operations**: Operations are applied to corresponding elements.

In [5]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
addition_result = tf.add(matrix1, matrix2)

In [6]:
multiplication_result = tf.matmul(matrix1, matrix2)

In [7]:
elementwise_product = tf.multiply(matrix1, matrix2)

### Part 2: Practical Implementation

#### Task 1: Creating and Manipulating Matrices

1. **Create a normal matrix A with dimensions 2x2 using TensorFlow's random_normal function. Display the values of matrix A.**


In [8]:
import tensorflow as tf
A = tf.random.normal([2, 2])
print(A)

tf.Tensor(
[[-0.21590132  1.5015147 ]
 [ 0.75708866  0.6191991 ]], shape=(2, 2), dtype=float32)


2. **Create a Gaussian matrix B with dimensions 2x2 using TensorFlow's truncated_normal function. Display the values of matrix B.**

In [9]:
B = tf.random.truncated_normal([2, 2])
print(B)

tf.Tensor(
[[-0.2074246  0.7127538]
 [ 0.898074   0.8731665]], shape=(2, 2), dtype=float32)


3. **Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.**

In [10]:
C = tf.random.normal([2, 2], mean=2, stddev=0.5)
print(C)

tf.Tensor(
[[1.3236707 1.8106565]
 [2.18122   2.136609 ]], shape=(2, 2), dtype=float32)


4. **Perform matrix addition between matrix A and matrix B, and store the result in matrix D.**

In [11]:
D = tf.add(A, B)
print(D)

tf.Tensor(
[[-0.4233259  2.2142684]
 [ 1.6551626  1.4923656]], shape=(2, 2), dtype=float32)


5. **Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.**

In [12]:
E = tf.matmul(C, D)
print(E)

tf.Tensor(
[[2.4365869 5.633124 ]
 [2.6130683 8.018409 ]], shape=(2, 2), dtype=float32)


#### Task 2: Performing Additional Matrix Operations

1. **Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.**

In [13]:
F = tf.random.uniform([2, 2])
print(F)

tf.Tensor(
[[0.5133691  0.51927435]
 [0.55514944 0.64095414]], shape=(2, 2), dtype=float32)


2. **Calculate the transpose of matrix F and store the result in matrix G.**

In [14]:
G = tf.transpose(F)
print(G)

tf.Tensor(
[[0.5133691  0.55514944]
 [0.51927435 0.64095414]], shape=(2, 2), dtype=float32)


3. **Calculate the element-wise exponential of matrix F and store the result in matrix H.**

In [15]:
H = tf.math.exp(F)
print(H)

tf.Tensor(
[[1.6709112 1.6808075]
 [1.7422013 1.8982912]], shape=(2, 2), dtype=float32)


4. **Create a matrix I by concatenating matrix F and matrix G horizontally.**

In [16]:
I = tf.concat([F, G], axis=1)
print(I)

tf.Tensor(
[[0.5133691  0.51927435 0.5133691  0.55514944]
 [0.55514944 0.64095414 0.51927435 0.64095414]], shape=(2, 4), dtype=float32)


5. **Create a matrix J by concatenating matrix F and matrix H vertically.**

In [17]:
J = tf.concat([F, H], axis=0)
print(J)

tf.Tensor(
[[0.5133691  0.51927435]
 [0.55514944 0.64095414]
 [1.6709112  1.6808075 ]
 [1.7422013  1.8982912 ]], shape=(4, 2), dtype=float32)


# **COMPLETE**